// UI
export const SWITCH_TAB = 'SWITCH_TAB';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const SET_USER_POSITION = 'SET_USER_POSITION';
export const SET_BROADCASTING = 'SET_BROADCASTING';
export const SET_DRIVER_STATUS = 'SET_DRIVER_STATUS';

// Settings (persisted to disk)
export const SET_VEHICLE_ID = 'SET_VEHICLE_ID';
export const SET_VEHICLE_TYPE = 'SET_VEHICLE_TYPE';
export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

// Taxi data
export const FETCH_TAXIS_START = 'FETCH_TAXIS_START';
export const FETCH_TAXIS_SUCCESS = 'FETCH_TAXIS_SUCCESS';
export const FETCH_TAXIS_ERROR = 'FETCH_TAXIS_ERROR';
export const SET_DRIVER_ASSET = 'SET_DRIVER_ASSET';
export const ASSET_OPERATION_START = 'ASSET_OPERATION_START';
export const ASSET_OPERATION_SUCCESS = 'ASSET_OPERATION_SUCCESS';
export const ASSET_OPERATION_ERROR = 'ASSET_OPERATION_ERROR';

// Ratings
export const FETCH_RATINGS_START = 'FETCH_RATINGS_START';
export const FETCH_RATINGS_SUCCESS = 'FETCH_RATINGS_SUCCESS';
export const FETCH_RATINGS_ERROR = 'FETCH_RATINGS_ERROR';
export const SET_MY_RATINGS = 'SET_MY_RATINGS';
export const RATING_OPERATION_START = 'RATING_OPERATION_START';
export const RATING_OPERATION_SUCCESS = 'RATING_OPERATION_SUCCESS';
export const RATING_OPERATION_ERROR = 'RATING_OPERATION_ERROR';
